name: Demo 6 - PR

# Can also be controled by specific branches or paths
on:
  pull_request:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  pr-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "I do a check on your PR"
